import type { Metadata } from "next";
import { Roboto, Gluten } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ weight: ["500", "900"], subsets: ["greek"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        {children}
      </body>
    </html>
  );
}
